name: create release action
description: Creates the tag and GitHub release, using conventional commits.

inputs:
  github_token:
    description: Github token
    required: true
  project_type:
    description: "The project's type (options: go, jvm)"
    required: false
    default: jvm
  go_version:
    description: The Go version to configure. If not provided, will use the one specified in `go.mod` file.
    required: false
  vault_token:
    description: The vault token
    required: false
  vault_addr:
    description: The vault addr
    required: false
  # sonar_token:
  #   description: The Sonar Token to use
  #   required: false
  # sonar_host_url:
  #   description: The Sonar host to use
  #   required: false
  artifactory_user:
    description: The artifactory user
    required: false
  artifactory_token:
    description: The artifactory password
    required: false
  check_command:
    description: The command to run to run checks and generate a code coverage report (Golang only).
    required: false
  gradle_check_and_submit_command:
    description: The gradle tasks to run in addition to ./gradlew check build (JVM only).
    required: false
    default: ./gradlew check build integrationTest

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - name: Fetch full history
      run: git fetch --prune --tags --unshallow
      shell: bash

    - name: Bump version and push tag
      id: push_tag
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ inputs.github_token }}
        default_bump: patch

    - name: Fetch Refresh
      run: git fetch --prune --tags
      shell: bash

    # - uses: armory-io/infra-github-actions/gradle-analyze-and-submit-to-sonar@master
    #   if: ${{ inputs.project_type == 'jvm' }}
    #   with:
    #     github_token: '${{ inputs.github_token }}'
    #     vault_addr: '${{ inputs.vault_addr }}'
    #     vault_token: '${{ inputs.vault_token }}'
    #     sonar_token: '${{ inputs.sonar_token }}'
    #     sonar_host_url: '${{ inputs.sonar_host_url }}'
    #     artifactory_user: '${{ inputs.artifactory_user }}'
    #     artifactory_token: '${{ inputs.artifactory_token }}'
    #     gradle_check_and_submit_command: '${{ inputs.gradle_check_and_submit_command }}'

    # - uses: armory-io/infra-github-actions/golang-analyze-and-submit-to-sonar@master
    #   if: ${{ inputs.project_type == 'go' && inputs.check_command != '' }}
    #   with:
    #     github_token: '${{ inputs.github_token }}'
    #     vault_addr: '${{ inputs.vault_addr }}'
    #     vault_token: '${{ inputs.vault_token }}'
    #     sonar_token: '${{ inputs.sonar_token }}'
    #     sonar_host_url: '${{ inputs.sonar_host_url }}'
    #     check_command: '${{ inputs.check_command }}'
    #     go_version: '${{ inputs.go_version }}'

    - name: Generate Changelog
      id: changelog
      env:
        NEW_TAG: ${{ steps.push_tag.outputs.new_tag }}
        PREVIOUS_TAG: ${{ steps.push_tag.outputs.previous_tag }}
      run: |
        set mode -x
        export CHANGELOG=`git log $NEW_TAG...$PREVIOUS_TAG --oneline`
        echo "CHANGELOG=$CHANGELOG"
        CHANGELOG="${CHANGELOG//$'%'/%25}"
        CHANGELOG="${CHANGELOG//$'\n'/%0A}"
        CHANGELOG="${CHANGELOG//$'\r'/%0D}"
        echo ::set-output name=CHANGELOG::$(echo -e "${CHANGELOG}")
      shell: bash

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.push_tag.outputs.new_tag }}
        name: ${{ steps.push_tag.outputs.new_version }}
        body: |
          ${{ steps.changelog.outputs.CHANGELOG }}
        draft: false
        prerelease: false
