name: pull requests analysis
description: Runs a projects checks/tests and submits results to SonarQube

inputs:
  github_token:
    description: The Github Token to use
    required: true
  sonar_token:
    description: The Sonar Token to use
    required: true
  sonar_host_url:
    description: The Sonar host to use
    required: true
  check_command:
    description: The command to generate a code coverage report
    required: false
    default: make check
  go_version:
    description: The Go version to configure
    required: false
    default: '1.18'
  vault_token:
    description: The vault token
    required: true
  vault_addr:
    description: The vault addr
    required: true

runs:
  using: composite
  steps:
    - name: Get temporary AWS credentials
      uses: armory-io/infra-github-actions/fetch-aws-credentials@master
      if: ${{ inputs.vault_addr != '' && inputs.vault_token != '' }}
      with:
        vault_addr: '${{ inputs.vault_addr }}'
        vault_token: '${{ inputs.vault_token }}'

    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        submodules: recursive

    - name: Fetch full history
      run: |
        git fetch --tags -f
        git fetch --prune --tags --unshallow
      shell: bash

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        go-version: ${{ inputs.go_version }}
        
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run Check 
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: >-
        ${{ inputs.check_command }}
      shell: bash

    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_host_url }}

    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.5"
        install-go: false

    - name: Upload Tests Reports to Github
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          build/reports/*
