name: pull requests analysis
description: Runs a projects checks/tests and submits results to SonarQube

inputs:
  github_token:
    description: The Github Token to use
    required: true
  sonar_token:
    description: The Sonar Token to use
    required: true
  sonar_host_url:
    description: The Sonar host to use
    required: true
  check_command:
    description: The command to generate a code coverage report
    required: false
    default: make coverage
  go_version:
    description: The Go version to configure
    required: false
    default: '1.16'

runs:
  using: composite
  steps:
    - name: Get temporary AWS Credentials
      env:
        VAULT_ADDR: ${{ inputs.vault_addr }}
        VAULT_TOKEN: ${{ inputs.vault_token }}
        AWS_REGION: us-west-2
        AWS_DEFAULT_REGION: us-west-2
      run: |
        wget --quiet https://releases.hashicorp.com/vault/1.5.5/vault_1.5.5_linux_amd64.zip
        unzip vault_1.5.5_linux_amd64.zip
        chmod +x ./vault
        export CREDS=$(./vault write -format json aws/hosted-services/sts/armory-cloud-github-actions-role ttl=60m || exit 1)
        AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r ".data.access_key")
        AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r ".data.secret_key")
        AWS_SESSION_TOKEN=$(echo $CREDS | jq -r ".data.security_token")
        echo "::add-mask::${AWS_ACCESS_KEY_ID}"
        echo "::add-mask::${AWS_SECRET_ACCESS_KEY}"
        echo "::add-mask::${AWS_SESSION_TOKEN}"
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        submodules: recursive

    - name: Fetch full history
      run: |
        git fetch --tags -f
        git fetch --prune --tags --unshallow
      shell: bash

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Run Check 
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: >-
        ${{ inputs.check_command }}
      shell: bash

    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_host_url }}
