name: pull requests analysis
description: Runs a projects checks/tests and submits results to SonarQube

inputs:
  github_token:
    description: The Github Token to use
    required: true
  sonar_token:
    description: The Sonar Token to use
    required: true
  sonar_host_url:
    description: The Sonar host to use
    required: true
  check_command:
    description: The command to generate a code coverage report
    required: false
    default: make coverage
  go_version:
    description: The Go version to configure
    required: false
    default: '1.16'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        submodules: recursive

    - name: Fetch full history
      run: |
        git fetch --tags -f
        git fetch --prune --tags --unshallow
      shell: bash

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Run Check 
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: >-
        ${{ inputs.check_command }}
      shell: bash

    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_host_url }}
