name: fetch aws credentials
description: Fetches AWS credentials from Vault

inputs:
  vault_token:
    description: The vault token
    required: true
  vault_addr:
    description: The vault addr
    required: true
  aws_account:
    description: The AWS account to fetch credentials from
    required: false
    default: armory-cloud-non-prod
  role:
    description: Vault role you want to assume
    required: false
    default: armory-cloud-github-actions-role


runs:
  using: composite
  steps:
    - name: Get AWS Credentials
      env:
        VAULT_ADDR: ${{ inputs.vault_addr }}
        VAULT_TOKEN: ${{ inputs.vault_token }}
        AWS_REGION: us-west-2
        AWS_DEFAULT_REGION: us-west-2
      run: |
        wget --quiet https://releases.hashicorp.com/vault/1.5.5/vault_1.5.5_linux_amd64.zip
        unzip -o vault_1.5.5_linux_amd64.zip
        chmod +x ./vault
        export CREDS=$(./vault write -format json aws/${{ inputs.aws_account }}/sts/{{ inputs.role }} ttl=60m || exit 1)
        AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r ".data.access_key")
        AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r ".data.secret_key")
        AWS_SESSION_TOKEN=$(echo $CREDS | jq -r ".data.security_token")
        echo "::add-mask::${AWS_ACCESS_KEY_ID}"
        echo "::add-mask::${AWS_SECRET_ACCESS_KEY}"
        echo "::add-mask::${AWS_SESSION_TOKEN}"
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $GITHUB_ENV
      shell: bash
