name: pull requests analysis
description: Runs a projects checks/tests and submits results to SonarQube

inputs:
  github_token:
    description: The Github Token to use
    required: true
  vault_token:
    description: The vault token
    required: true
  vault_addr:
    description: The vault addr
    required: true
  sonar_token:
    description: The Sonar Token to use
    required: true
  sonar_host_url:
    description: The Sonar host to use
    required: true
  artifactory_user:
    description: The artifactory user
    required: true
  artifactory_token:
    description: The artifactory password
    required: true
  gradle_check_and_submit_command:
    description: The gradle tasks to run in addition to ./gradlew check build sonarqube
    required: false
    default: ./gradlew check build integrationTest sonarqube

runs:
  using: composite
  steps:
    - name: Get temporary AWS Credentials
      env:
        ROLE_NAME: armory-cloud-github-actions-role
        VAULT_ADDR: ${{ inputs.vault_token }}
        VAULT_TOKEN: ${{ inputs.vault_addr }}
        AWS_REGION: us-west-2
        AWS_DEFAULT_REGION: us-west-2
      run: |
        wget --quiet https://releases.hashicorp.com/vault/1.5.5/vault_1.5.5_linux_amd64.zip
        unzip vault_1.5.5_linux_amd64.zip
        chmod +x ./vault
        export CREDS=$(./vault write -format json aws/dev/sts/${ROLE_NAME} ttl=60m || exit 1)
        AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r ".data.access_key")
        AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r ".data.secret_key")
        AWS_SESSION_TOKEN=$(echo $CREDS | jq -r ".data.security_token")
        echo "::add-mask::${AWS_ACCESS_KEY_ID}"
        echo "::add-mask::${AWS_SECRET_ACCESS_KEY}"
        echo "::add-mask::${AWS_SESSION_TOKEN}"
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $GITHUB_ENV
      shell: bash
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        submodules: recursive
    - name: Fetch full history
      run: |
        git fetch --tags -f
        git fetch --prune --tags --unshallow
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Run Checks and Submit to SonarQube
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_host_url }}
      run: >-
        ${{ inputs.gradle_check_and_submit_command }}
        -Partifactory_user=${{ inputs.artifactory_user }}
        -Partifactory_password=${{ inputs.artifactory_token }}
      shell: bash
    - name: Upload Tests Reports to Github
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          integration/build/reports/*