name: Build and Publish Container Action
description: Invokes gradle to build artifact and bake the docker container and push it to artifactory

inputs:
  artifactory_user:
    description: The artifactory user
    required: true
  artifactory_token:
    description: The artifactory token
    required: true
  registry:
    description: The registry to login with
    required: true
  gradle_build_docker_push_command:
    description: The gradle tasks to run in addition to ./gradlew check build sonarqube
    required: false
    default: ./gradlew build -x check dockerPush
  java_version:
    description: The Java Version to configure
    required: false
    default: '17'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.tag_name }}

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.java_version }}

    - name: Login to Artifactory
      run: |
        docker login -u ${{ inputs.artifactory_user }} -p ${{ inputs.artifactory_token }} ${{ inputs.registry }}
      shell: bash

    - name: Build Artifact
      run: >-
        ${{ inputs.gradle_build_docker_push_command }}
        -Partifactory_user=${{inputs.artifactory_user}}
        -Partifactory_password=${{inputs.artifactory_token}}
      shell: bash